# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.1"

  # config.vm.box_check_update = false
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
  # in case of runing vagrant provision
     ps auxwf|grep "docker daemon"|grep -v grep
     if [ $? -eq 1 ]; then
       sudo service docker start
     fi
  # install docker if it is not installed
     if [ ! -f /usr/bin/docker ]; then
       echo "Installing and starting Docker..."
       curl -sSL https://get.docker.com/ | sh
       service docker start
     fi
  # install unzip
     if [ ! -f /usr/bin/unzip ]; then
       echo "Downloadin upzip..."
       yum -y install unzip
     fi

  # install packer
     if [ ! -f /opt/packer/packer ]; then
       echo "Downloading Packer (126MB)..."
       wget -q https://dl.bintray.com/mitchellh/packer/packer_0.8.6_linux_amd64.zip
       mkdir -p /opt/packer; unzip -o packer_0.8.6_linux_amd64.zip -d /opt/packer
     fi
  # install vagrant
     if [ ! -f /usr/bin/vagrant ]; then
       echo "Installing Vagrant..."
       wget -q https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.rpm
       rpm -ihv vagrant_1.7.4_x86_64.rpm
     fi

  # predownload some useful docker images
     docker pull centos
     docker pull orchardup/mysql:latest
  SHELL
end
